from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    BACKEND_NOT_RADEON = "BACKEND_NOT_RADEON"
    BACKEND_PROBE_FAILED = "BACKEND_PROBE_FAILED"
    TORCH_MISSING = "TORCH_MISSING"
    GENESIS_MISSING = "GENESIS_MISSING"
    GPU_NOT_VISIBLE = "GPU_NOT_VISIBLE"
    CONFIG_INVALID = "CONFIG_INVALID"
    CONFIG_MISSING = "CONFIG_MISSING"
    CONTROLLER_UNKNOWN = "CONTROLLER_UNKNOWN"
    EVIDENCE_FILE_MISSING = "EVIDENCE_FILE_MISSING"
    EVIDENCE_SCHEMA_INVALID = "EVIDENCE_SCHEMA_INVALID"
    EVIDENCE_HASH_MISMATCH = "EVIDENCE_HASH_MISMATCH"
    EVIDENCE_AGGREGATE_MISMATCH = "EVIDENCE_AGGREGATE_MISMATCH"
    SUITE_CONTAMINATED = "SUITE_CONTAMINATED"
    EPISODE_UNMATCHED = "EPISODE_UNMATCHED"
    EPISODE_CONDITIONS_DIVERGED = "EPISODE_CONDITIONS_DIVERGED"
    EPISODE_DUPLICATE = "EPISODE_DUPLICATE"
    EPISODE_SUITE_MIXED = "EPISODE_SUITE_MIXED"
    EPISODE_CONTROLLER_MIXED = "EPISODE_CONTROLLER_MIXED"
    SAMPLE_EMPTY = "SAMPLE_EMPTY"
    SAMPLE_INVALID = "SAMPLE_INVALID"
    SCENE_OFFSETS_UNAVAILABLE = "SCENE_OFFSETS_UNAVAILABLE"
    SCENE_LAYOUT_MISALIGNED = "SCENE_LAYOUT_MISALIGNED"


class CruxError(Exception):
    code: ErrorCode

    def __init__(self, code: ErrorCode, message: str) -> None:
        super().__init__(f"[{code}] {message}")
        self.code = code
        self.message = message


class ConfigError(CruxError):
    pass


class EvidenceError(CruxError):
    pass


class QualificationError(CruxError):
    pass


class BackendError(CruxError):
    pass
